Count,Message,Traceback,Nodes
3,No users present after waiting.,"  File ""/opt/venv/lib/python3.11/site-packages/locust/user/task.py"", line 340, in run
    self.execute_next_task()
  File ""/opt/venv/lib/python3.11/site-packages/locust/user/task.py"", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File ""/opt/venv/lib/python3.11/site-packages/locust/user/task.py"", line 385, in execute_task
    task(self)
  File ""/mnt/locust/common/postservice.py"", line 63, in like_post
    post_id, user_id = self.get_post_and_user_pair()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/mnt/locust/common/postservice.py"", line 95, in get_post_and_user_pair
    if_no_user_exists_wait()
  File ""/mnt/locust/common/util.py"", line 26, in if_no_user_exists_wait
    raise Exception(""No users present after waiting."")
","78721c0db6e1_3b0ae162029c449d841738615a96a734, a98624c0a912_32b32b4550d44934b03d0a0a3003fdbd, 87842afeaac4_d78376bd83fc4b75b6f2765517c2ac99"
1,No users present after waiting.,"  File ""/opt/venv/lib/python3.11/site-packages/locust/user/task.py"", line 340, in run
    self.execute_next_task()
  File ""/opt/venv/lib/python3.11/site-packages/locust/user/task.py"", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File ""/opt/venv/lib/python3.11/site-packages/locust/user/task.py"", line 385, in execute_task
    task(self)
  File ""/mnt/locust/common/notificationservice.py"", line 12, in count_notifications
    if_no_user_exists_wait()
  File ""/mnt/locust/common/util.py"", line 26, in if_no_user_exists_wait
    raise Exception(""No users present after waiting."")
",87842afeaac4_d78376bd83fc4b75b6f2765517c2ac99
1,No users present after waiting.,"  File ""/opt/venv/lib/python3.11/site-packages/locust/user/task.py"", line 340, in run
    self.execute_next_task()
  File ""/opt/venv/lib/python3.11/site-packages/locust/user/task.py"", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File ""/opt/venv/lib/python3.11/site-packages/locust/user/task.py"", line 385, in execute_task
    task(self)
  File ""/mnt/locust/common/postservice.py"", line 76, in get_post_image
    self.if_no_post_exists_create()
  File ""/mnt/locust/common/postservice.py"", line 59, in if_no_post_exists_create
    self.create_post()
  File ""/mnt/locust/common/postservice.py"", line 18, in create_post
    if_no_user_exists_wait()
  File ""/mnt/locust/common/util.py"", line 26, in if_no_user_exists_wait
    raise Exception(""No users present after waiting."")
",a98624c0a912_32b32b4550d44934b03d0a0a3003fdbd
3,No users present after waiting.,"  File ""/opt/venv/lib/python3.11/site-packages/locust/user/task.py"", line 340, in run
    self.execute_next_task()
  File ""/opt/venv/lib/python3.11/site-packages/locust/user/task.py"", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File ""/opt/venv/lib/python3.11/site-packages/locust/user/task.py"", line 385, in execute_task
    task(self)
  File ""/mnt/locust/common/feedservice.py"", line 12, in get_users_feed
    if_no_user_exists_wait()
  File ""/mnt/locust/common/util.py"", line 26, in if_no_user_exists_wait
    raise Exception(""No users present after waiting."")
","a98624c0a912_32b32b4550d44934b03d0a0a3003fdbd, 87842afeaac4_d78376bd83fc4b75b6f2765517c2ac99"
